Criação completo da rota get_student
Maua-Dev/selfie_mss_student pull request #1
Opened 2022-10-05 12:03 UTC by VgsStudio

Criação completa, desde entidades até o presenter, tudo com teste unitário.

2022-10-06 23:38 UTC, Brvilardi requested changes

2022-10-06 23:38 UTC, Brvilardi commented on src/domain/entities/student.py
> +        if (ra == None or len(ra) != 8):
Verificar se é número

2022-10-06 23:38 UTC, Brvilardi commented on src/domain/entities/student.py
> +        if (ra == None or len(ra) != 8):
19003-1 seria válido

2022-10-06 23:38 UTC, Brvilardi commented on src/domain/entities/student.py
> +        if('@' not in email or '.' not in email):
implementar validacao por regex

2022-10-06 23:38 UTC, Brvilardi commented on src/domain/enums/situation_enum.py
> +    INREVIEW = "Em análise"
IN_REVIEW

2022-10-06 23:38 UTC, Brvilardi commented on src/infra/repositories/student_repository_mock.py
> +    def get_student(self, ra:str, email:str) -> Student:
so faz com RA, tira email

2022-10-06 23:38 UTC, Brvilardi commented on src/modules/get_student/get_student_controller.py
> +class GetStudentController():
classe sem heranca, nao coloca ()

class GetStudentController:

2022-10-06 23:38 UTC, Brvilardi commented on src/modules/get_student/get_student_controller.py
> +                raise MissingParameters('email')
tira o email

2022-10-06 23:38 UTC, Brvilardi commented on src/modules/get_student/get_student_controller.py
> +
limpar o campo ra → tira ponto, traco e espaço (sem dar erro)

2022-10-06 23:38 UTC, Brvilardi commented on src/modules/get_student/get_student_usecase.py
> +    def __call__(self, ra:str, email:str) -> Student:
tirar email

2022-10-06 23:38 UTC, Brvilardi commented on src/modules/get_student/get_student_usecase.py
> +        student = self.repo.get_student(ra=ra, email=email)
validar se é um RA válido - seria legal ver com alguem da Mauá o calculo de digito para validação

2022-10-06 23:38 UTC, Brvilardi commented on tests/modules/get_student/test_get_student_presenter.py
> +    def test_get_subject(self):
fazer um novo teste para cada erro 400

2022-10-07 02:23 UTC, VgsStudio commented on src/domain/entities/student.py
> +        if (ra == None or len(ra) != 8):
ok

2022-10-07 02:23 UTC, VgsStudio commented on src/domain/enums/situation_enum.py
> +    INREVIEW = "Em análise"
ok

2022-10-07 02:26 UTC, VgsStudio commented on src/modules/get_student/get_student_controller.py
> +class GetStudentController():
ok

2022-10-08 00:19 UTC, VgsStudio commented on src/infra/repositories/student_repository_mock.py
> +    def get_student(self, ra:str, email:str) -> Student:
ok

2022-10-08 00:22 UTC, VgsStudio commented on src/modules/get_student/get_student_usecase.py
> +    def __call__(self, ra:str, email:str) -> Student:
ok

2022-10-08 00:22 UTC, VgsStudio commented on src/modules/get_student/get_student_controller.py
> +                raise MissingParameters('email')
ok

2022-10-08 00:35 UTC, VgsStudio commented on src/modules/get_student/get_student_usecase.py
> +        student = self.repo.get_student(ra=ra, email=email)
ok

2022-10-08 18:51 UTC, Brvilardi requested changes

2022-10-08 18:51 UTC, Brvilardi commented on tests/modules/get_student/test_get_student_presenter.py
> +    def test_get_student(self):
testar se o body esta mostrando o que esperamos no view model quando acha um Student válido

2022-10-08 18:52 UTC, Brvilardi requested changes

2022-10-08 18:52 UTC, Brvilardi commented on src/modules/get_student/get_student_controller.py
> +from dataclasses import replace
TIRAR OS "." DE TODAS AS MENSAGENS DE ERRO

2022-10-08 19:22 UTC, VgsStudio commented on tests/modules/get_student/test_get_student_presenter.py
> +    def test_get_student(self):
ok

2022-10-08 19:31 UTC, Brvilardi requested changes

2022-10-08 19:31 UTC, Brvilardi commented on tests/modules/get_student/test_get_student_presenter.py
> +        result = {
trocar result por expectedResult

2022-10-08 19:51 UTC, merged