Get all selfies
Maua-Dev/selfie_mss_student pull request #11
Opened 2022-10-26 02:16 UTC by VgsStudio

rota get_all selfies

## FAVOR APROVAR PRIMEIRO O CHECK STUDENT HAS APPROVED SELFIE PQ ESSE DEPDENDE DAQUELE PULL REQUEST

2022-10-27 12:18 UTC, Brvilardi requested changes

2022-10-27 12:18 UTC, Brvilardi commented on src/modules/get_all_selfies/app/get_all_selfies_controller.py
> +        viewmodel = GetAllSelfiesViewModel(all_selfies)
o que acontece se all_selfies for []?

2022-10-27 13:43 UTC, VgsStudio commented on src/modules/get_all_selfies/app/get_all_selfies_controller.py
> +        viewmodel = GetAllSelfiesViewModel(all_selfies)
retorna uma lista vazia no viewmodel

2022-10-29 20:36 UTC, Brvilardi approved these changes
LGTM

2022-10-29 20:37 UTC, merged