Request upload selfie
Maua-Dev/selfie_mss_student pull request #20
Opened 2022-11-13 02:47 UTC by JoaoVitorBranco

2022-11-16 23:50 UTC, Brvilardi requested changes
arrumem pls

2022-11-16 23:50 UTC, Brvilardi commented on src/modules/create_selfie/app/create_selfie_controller.py
> +    def __call__(self, request: dict) -> HttpResponse:
o controller continua recebendo um HttpRequest, a diferenca é só no presenter

2022-11-16 23:50 UTC, Brvilardi commented on src/modules/create_selfie/app/create_selfie_presenter.py
> -    httpRequest = LambdaHttpRequest(data=event)
httpRequest = HttpRequest(body=event["body"], etc)

2022-11-16 23:50 UTC, Brvilardi commented on src/modules/create_selfie/app/create_selfie_usecase.py
> +from src.shared.helpers.functions.read_automatic_review import read_automatic_review
colocar isso como um metodo estatico da classe AutomaticReview

2022-11-16 23:50 UTC, Brvilardi commented on src/modules/create_selfie/app/create_selfie_usecase.py
> +            state=STATE.PENDING_REVIEW if not automaticReviewInstance.automaticallyRejected else STATE.DECLINED,
LINDO 😍

2022-11-16 23:50 UTC, Brvilardi commented on src/modules/create_selfie/app/create_selfie_usecase.py
> +            rejectionReasons=[REJECTION_REASON.NONE] if not automaticReviewInstance.automaticallyRejected else automaticReviewInstance.rejectionReasons,
pergunta: por que colocar NONE ao invés de uma lista vazia?

2022-11-16 23:50 UTC, Brvilardi commented on src/modules/create_selfie/app/create_selfie_usecase.py
> +            rejectionReasons=[REJECTION_REASON.NONE] if not automaticReviewInstance.automaticallyRejected else automaticReviewInstance.rejectionReasons,
outra: as rejectionReasions do automaticReviewIntance sao no mesmo enum que Selfie?

2022-11-16 23:50 UTC, Brvilardi commented on src/modules/create_selfie/app/create_selfie_viewmodel.py
>  class StudentViewModel:
isso deveria ser Selfie ne? 🙈

2022-11-16 23:50 UTC, Brvilardi commented on src/modules/update_selfie/app/update_selfie_controller.py
> +            if not request.body.get("new_rejectionReasons") is None:
change to "new_rejectionReasons" in request.body

2022-11-16 23:50 UTC, Brvilardi commented on src/modules/validate_selfie/app/validate_selfie_controller.py
> +    def __call__(self, request:dict) -> dict:
request should be HttpRequest

2022-11-16 23:50 UTC, Brvilardi commented on src/modules/validate_selfie/app/validate_selfie_controller.py
> +            automaticReview = self.validateSelfieUsecase(rekognitionResult=request.get('rekognitionResult'))
debater sobre rekognition chegar ate usecase - por enquanto beleza, mas poderia ser melhor

2022-11-16 23:50 UTC, Brvilardi commented on src/modules/validate_selfie/app/validate_selfie_presenter.py
> +
instanciar http request

2022-11-16 23:50 UTC, Brvilardi commented on src/modules/validate_selfie/app/validate_selfie_usecase.py
> +        if rekognitionResult.get("Labels") is None:
if "Labels" in rekognitionResult

2022-11-16 23:50 UTC, Brvilardi commented on src/modules/validate_selfie/app/validate_selfie_usecase.py
> +            if len(label["Instances"]) == 0:
colocar comentario explicando a diferenca de cada

2022-11-16 23:50 UTC, Brvilardi commented on src/modules/validate_selfie/app/validate_selfie_usecase.py
> +        for label in labels:
colocar um if antes pra ver a confianca

2022-11-16 23:50 UTC, Brvilardi commented on src/modules/validate_selfie/app/validate_selfie_usecase.py
> +                allLabels.append(labelDict)
nameSet.add(labelDict["label"])

2022-11-16 23:50 UTC, Brvilardi commented on src/modules/validate_selfie/app/validate_selfie_usecase.py
> +        if not all(name in names for name in ValidationLists.OBJECTS_REQUIRED.keys()):
🙈  https://www.programiz.com/python-programming/methods/set/issubset

2022-11-16 23:50 UTC, Brvilardi commented on src/modules/validate_selfie/app/validate_selfie_usecase.py
> +            rejectionReasons = rejectionReasons + [name for name in ValidationLists.PARENTS_REQUIRED.values() if name not in names]
🐒 list.extend

2022-11-16 23:50 UTC, Brvilardi commented on src/shared/helpers/functions/read_automatic_review.py
> +def read_automatic_review(automaticReview: dict) -> AutomaticReview:
jogar isso como metodo estatico do autmatic review

2022-11-18 02:49 UTC, Brvilardi commented
@JoaoVitorBranco coloquei as coisas do dynamo, please arruma as outras

2022-11-18 12:48 UTC, JoaoVitorBranco commented on src/modules/create_selfie/app/create_selfie_usecase.py
> +            rejectionReasons=[REJECTION_REASON.NONE] if not automaticReviewInstance.automaticallyRejected else automaticReviewInstance.rejectionReasons,
Primeiro: não sei, foi uma escolha aleatória kkkkkk vou alterar
Segundo: são (acho q a gnt tinha conversado disso em alguma daily)

2022-11-18 12:49 UTC, JoaoVitorBranco commented on src/modules/create_selfie/app/create_selfie_usecase.py
> +            rejectionReasons=[REJECTION_REASON.NONE] if not automaticReviewInstance.automaticallyRejected else automaticReviewInstance.rejectionReasons,
Sobre a primeira: também acho q a gnt tiha discutido isso, acho que era para padronizar o tipo de mensagem que estará dentro de rejectionReasons (List[ENUM])

2022-11-18 13:23 UTC, Brvilardi commented on src/modules/create_selfie/app/create_selfie_usecase.py
> +            rejectionReasons=[REJECTION_REASON.NONE] if not automaticReviewInstance.automaticallyRejected else automaticReviewInstance.rejectionReasons,
se vc concorda com isso, eu concordo tambem, essa so pra entender se era de graça

2022-11-18 13:31 UTC, JoaoVitorBranco commented on src/modules/create_selfie/app/create_selfie_usecase.py
> +            rejectionReasons=[REJECTION_REASON.NONE] if not automaticReviewInstance.automaticallyRejected else automaticReviewInstance.rejectionReasons,
😍🤗

2022-11-18 14:29 UTC, JoaoVitorBranco commented on src/modules/create_selfie/app/create_selfie_viewmodel.py
>  class StudentViewModel:
AAAAHHH MACAQUEI EIN

2022-11-18 14:32 UTC, JoaoVitorBranco commented on src/modules/create_selfie/app/create_selfie_viewmodel.py
>  class StudentViewModel:
Não entendi... a selfie não é o retorno do CreateSelfieViewModel?

2022-11-18 15:10 UTC, JoaoVitorBranco commented on src/modules/validate_selfie/app/validate_selfie_controller.py
> +            automaticReview = self.validateSelfieUsecase(rekognitionResult=request.get('rekognitionResult'))
O melhor seria instanciar de prima um rekognitionResult e dps ir passando?

2022-11-18 15:21 UTC, Brvilardi commented on src/modules/create_selfie/app/create_selfie_viewmodel.py
>  class StudentViewModel:
@JoaoVitorBranco o nome da Classe, nao deveria ser CreateSelfieViewModel? Esta StudentViewModel

2022-11-18 15:22 UTC, Brvilardi commented on src/modules/validate_selfie/app/validate_selfie_controller.py
> +            automaticReview = self.validateSelfieUsecase(rekognitionResult=request.get('rekognitionResult'))
seria melhor, nao se se "O" melhor

2022-11-18 15:38 UTC, JoaoVitorBranco commented on src/modules/validate_selfie/app/validate_selfie_controller.py
> +            automaticReview = self.validateSelfieUsecase(rekognitionResult=request.get('rekognitionResult'))
Entendi. Mas vc disse "por enquanto", então tenho que alterar?

2022-11-18 15:39 UTC, JoaoVitorBranco commented on src/modules/create_selfie/app/create_selfie_viewmodel.py
>  class StudentViewModel:
![image](https://user-images.githubusercontent.com/85962841/202743022-c6d400d7-babd-4642-ae3a-6a18349835b3.png)
![image](https://user-images.githubusercontent.com/85962841/202743082-7c63e2ee-ac99-4c93-9454-e50fd8ebb596.png)
ainda não entendi...

2022-11-18 19:06 UTC, Brvilardi approved these changes
sera que um dia os passaros vai nadar?

2022-11-18 19:06 UTC, merged