Selfie upload workflow
Maua-Dev/selfie_mss_student pull request #30
Opened 2022-11-20 19:55 UTC by Brvilardi

2022-11-21 13:12 UTC, VgsStudio requested changes

2022-11-21 13:12 UTC, VgsStudio commented on src/modules/create_selfie/app/create_selfie_presenter.py
>      controller = CreateSelfieController(usecase)
isso é porque vamos receber um http request ne

2022-11-21 13:12 UTC, VgsStudio commented on src/modules/request_upload_selfie/app/request_upload_selfie_controller.py
> +            print(f"ViewMode: {viewmodel}")
vc vaideixar esse print ai por que?!

2022-11-21 13:12 UTC, VgsStudio commented on src/shared/infra/repositories/selfie_repository_s3.py
> +            presignedUrl = self.s3_client.generate_presigned_url(
mudou para pressigned url por que? 
qual a vantagem?
mudar o nome da função?

2022-11-21 22:50 UTC, Brvilardi commented on src/modules/create_selfie/app/create_selfie_presenter.py
>      controller = CreateSelfieController(usecase)
NAO!

2022-11-21 22:50 UTC, Brvilardi commented on src/modules/request_upload_selfie/app/request_upload_selfie_controller.py
> +            print(f"ViewMode: {viewmodel}")
nao vou, nice catch

2022-11-22 01:02 UTC, VgsStudio requested changes

2022-11-22 01:02 UTC, VgsStudio commented on src/modules/create_selfie/app/create_selfie_presenter.py
> +    print(event)
tira o print

2022-11-22 01:02 UTC, VgsStudio commented on src/modules/create_selfie/app/create_selfie_presenter.py
> +    print(httpResponse.toDict())
print

2022-11-22 01:02 UTC, VgsStudio commented on src/modules/request_upload_selfie/app/request_upload_selfie_presenter.py
> +    print(response)
print

2022-11-22 01:02 UTC, VgsStudio commented on src/shared/infra/repositories/load_student_mock_to_dynamo.py
>      # os.environ["STAGE"] = "TEST"
comment top

2022-11-22 01:02 UTC, VgsStudio commented on src/shared/infra/repositories/selfie_repository_s3.py
> +        try:
tira se achar pertinente!!

2022-11-22 01:02 UTC, VgsStudio commented on src/modules/validate_selfie/app/validate_selfie_presenter.py
> +    body = {}
dict()

2022-11-22 01:03 UTC, VgsStudio approved these changes
LGTM

2022-11-22 01:51 UTC, merged