Review branch
Maua-Dev/selfie_mss_student pull request #42
Opened 2022-12-02 18:08 UTC by VgsStudio

Apenas aceito o pull request quando estiver pronto tudo de review

2022-12-10 21:35 UTC, Brvilardi requested changes

2022-12-10 21:35 UTC, Brvilardi commented on src/shared/infra/repositories/student_repository_mock.py
> +        review = self.update_review(reviewerRa=reviewerRa, idReview=idReview, idSelfie=idSelfie, studentRa=studentRa, new_state=REVIEW_STATE.APPROVED)
faltou atualizar o state da selfie

2022-12-10 21:35 UTC, Brvilardi commented on src/shared/infra/repositories/student_repository_mock.py
> +        review = self.update_review(
faltou atualizar o state da selfie

2022-12-10 21:35 UTC, Brvilardi commented on src/modules/get_approved_selfies_by_reviewer/app/get_approved_selfies_by_reviewer_usecase.py
> +        return reviewer, reviews
se o metodo retornar uma lista de reviews ele deve chamar get reviews by reviwer.

2022-12-10 21:35 UTC, Brvilardi commented on src/modules/get_rejected_selfies_by_reviewer/app/get_rejected_selfies_by_reviewer_usecase.py
> +        return reviewer, reviews
se retornar reviews tem sque ser get reviews e nao selgies

2022-12-10 21:35 UTC, Brvilardi commented on src/modules/get_review/app/get_review_usecase.py
> +        review = self.repo.get_review(reviewerRa=reviewerRa, idReview=idReview, idSelfie=idSelfie, studentRa=studentRa)
porque precisa passar o reviewerRA?

2022-12-10 21:35 UTC, Brvilardi commented on src/modules/get_selfies_to_review/app/get_selfies_to_review_controller.py
> +            reviews, reviewer = self.getSelfiesToReviewUsecase(*args)
porque nao passar direto? Essa forma de fazer ficou meio ruim de ler

2022-12-10 21:35 UTC, Brvilardi commented on src/modules/get_selfies_to_review/app/get_selfies_to_review_controller.py
> +            args = (request.query_params.get('reviewerRa'), int(request.query_params.get('nSelfies'))) if request.query_params.get('nSelfies') != None else (request.query_params.get('reviewerRa'),)
request.query_params.get('nSelfies') != None → acho ruim de ler, prefiro algo tipo "nSelfies" in  request.query_params

2022-12-10 21:35 UTC, Brvilardi commented on src/modules/get_selfies_to_review/app/get_selfies_to_review_controller.py
> +            reviews, reviewer = self.getSelfiesToReviewUsecase(*args)
se for por conta de valor padrao, acho melhor usar outra alternativa. Uma possibilidade é nao ter nSelfies como um argumento da funcao, coloca no __call__ do usecase tipo (ra, **kwargs) ai checa se 'nSelfies' está no kwargs e é diferente de None, se nao colocar 10

2022-12-10 21:35 UTC, Brvilardi commented on src/modules/get_selfies_to_review/app/get_selfies_to_review_usecase.py
> +        return self.repo.get_selfies_to_review(reviewerRa=reviewerRa, nSelfies=nSelfies)
deveriamos quebrar isso em uns 3 metodos? Acho que é muita responsabilidade e regra de negocio em um metodo só. Precisamos entender a questao da transacionalidade no Dynamo antes

2022-12-12 01:01 UTC, JoaoVitorBranco commented on src/shared/infra/repositories/student_repository_mock.py
> +        review = self.update_review(reviewerRa=reviewerRa, idReview=idReview, idSelfie=idSelfie, studentRa=studentRa, new_state=REVIEW_STATE.APPROVED)
O "update_review" já não atualiza o state da selfie? (chamando o "update_selfie"?)
![image](https://user-images.githubusercontent.com/85962841/206940440-7e26ec7b-02a4-41e6-8705-ed27689e9272.png)

2022-12-12 01:01 UTC, JoaoVitorBranco commented on src/shared/infra/repositories/student_repository_mock.py
> +        review = self.update_review(
⬆

2022-12-12 01:02 UTC, JoaoVitorBranco commented on src/modules/get_approved_selfies_by_reviewer/app/get_approved_selfies_by_reviewer_usecase.py
> +        return reviewer, reviews
reviewer*

2022-12-12 01:02 UTC, JoaoVitorBranco commented on src/modules/get_rejected_selfies_by_reviewer/app/get_rejected_selfies_by_reviewer_usecase.py
> +        return reviewer, reviews
selfies

2022-12-12 01:04 UTC, JoaoVitorBranco commented on src/modules/get_review/app/get_review_usecase.py
> +        review = self.repo.get_review(reviewerRa=reviewerRa, idReview=idReview, idSelfie=idSelfie, studentRa=studentRa)
Faz sentido não precisar... o reviewIdentifier já basta...

2022-12-12 01:22 UTC, VgsStudio commented on src/modules/get_approved_selfies_by_reviewer/app/get_approved_selfies_by_reviewer_usecase.py
> +        return reviewer, reviews
OK()

2022-12-12 01:22 UTC, VgsStudio commented on src/modules/get_rejected_selfies_by_reviewer/app/get_rejected_selfies_by_reviewer_usecase.py
> +        return reviewer, reviews
OK()

2022-12-12 01:31 UTC, JoaoVitorBranco commented on src/modules/get_review/app/get_review_usecase.py
> +        review = self.repo.get_review(reviewerRa=reviewerRa, idReview=idReview, idSelfie=idSelfie, studentRa=studentRa)
✅

2022-12-12 01:32 UTC, JoaoVitorBranco commented on src/modules/get_rejected_selfies_by_reviewer/app/get_rejected_selfies_by_reviewer_usecase.py
> +        return reviewer, reviews
✅

2022-12-12 01:32 UTC, JoaoVitorBranco commented on src/modules/get_approved_selfies_by_reviewer/app/get_approved_selfies_by_reviewer_usecase.py
> +        return reviewer, reviews
✅

2022-12-12 02:19 UTC, Brvilardi commented on src/shared/infra/repositories/student_repository_mock.py
> +        review = self.update_review(reviewerRa=reviewerRa, idReview=idReview, idSelfie=idSelfie, studentRa=studentRa, new_state=REVIEW_STATE.APPROVED)
aonde ta mudando isso? Usecase? Repo?

2022-12-12 23:49 UTC, JoaoVitorBranco commented on src/shared/infra/repositories/student_repository_mock.py
> +        review = self.update_review(reviewerRa=reviewerRa, idReview=idReview, idSelfie=idSelfie, studentRa=studentRa, new_state=REVIEW_STATE.APPROVED)
Repo

2022-12-13 00:55 UTC, Brvilardi commented on src/modules/get_selfies_to_review/app/get_selfies_to_review_controller.py
> +            args = (request.query_params.get('reviewerRa'), int(request.query_params.get('nSelfies'))) if request.query_params.get('nSelfies') != None else (request.query_params.get('reviewerRa'),)
![image](https://user-images.githubusercontent.com/62917140/207199773-31dc538a-9dfa-4329-ac0a-11ccc094a3e5.png)

2022-12-13 00:56 UTC, Brvilardi commented on src/modules/get_selfies_to_review/app/get_selfies_to_review_controller.py
> +            args = (request.query_params.get('reviewerRa'), int(request.query_params.get('nSelfies'))) if request.query_params.get('nSelfies') != None else (request.query_params.get('reviewerRa'),)
⬆️

2022-12-13 00:56 UTC, Brvilardi commented on src/modules/get_selfies_to_review/app/get_selfies_to_review_controller.py
> +            reviews, reviewer = self.getSelfiesToReviewUsecase(*args)
⬇️

2022-12-13 00:57 UTC, Brvilardi commented on src/modules/get_rejected_selfies_by_reviewer/app/get_rejected_selfies_by_reviewer_usecase.py
> +        return reviewer, reviews
> selfies*

n entendi...

2022-12-15 00:18 UTC, VgsStudio commented
![image](https://user-images.githubusercontent.com/81604963/207742908-a34e1abe-d698-4bd2-9a34-a6fa005c8e39.png)

LGTM 

😍

2022-12-15 00:45 UTC, Brvilardi approved these changes
SOLLER FALOU QUE PODE APROVAR (RESPONSABILIDADE 100% EXCLUSIVA DELE) 🦑

2022-12-15 01:41 UTC, JoaoVitorBranco commented
👁👁
👂   🐽    👂
       👄

2022-12-15 01:43 UTC, merged