Refat get all students
Maua-Dev/selfie_mss_student pull request #48
Opened 2022-12-08 21:10 UTC by VgsStudio

Agora o repo precisa devolver uma lista de students aprovados (scan nele) e no usecase verifica se o student em questao está na lista de apovados para retornar o status STUDENT_STATE.APPROVED

2022-12-09 00:47 UTC, Brvilardi requested changes

2022-12-09 00:47 UTC, Brvilardi commented on src/modules/get_all_students/app/get_all_students_usecase.py
> +            group_selfies_by_ra[selfie.student.ra]["selfies"].append(selfie)
colocar um if ou try pra se nao existir o RA → nao subir um erro

2022-12-09 00:47 UTC, Brvilardi commented on src/modules/get_all_students/app/get_all_students_usecase.py
> +            selfies, student = group_selfies_by_ra[raKey]['selfies'], group_selfies_by_ra[raKey]["student"]
nao fica melhor declarar em linhas diferentes?

2022-12-09 00:47 UTC, Brvilardi commented on src/modules/get_all_students/app/get_all_students_usecase.py
> +            elif any([selfie.state == STATE.APPROVED for selfie in selfies]): status = STUDENT_STATE.APPROVED
se isso funciona é lindo

2022-12-09 00:47 UTC, Brvilardi commented on src/shared/domain/repositories/student_repository_interface.py
> +    def get_all_students(self) -> List[Student]:
na vdd é um List[dict], nao?

2022-12-09 11:50 UTC, VgsStudio commented on src/modules/get_all_students/app/get_all_students_usecase.py
> +            elif any([selfie.state == STATE.APPROVED for selfie in selfies]): status = STUDENT_STATE.APPROVED
funciona papai, ele faz uma lista de [True, False] e se tiver qualquer um True o resultado final é True!

Passou nos testes! Viva o TDD!

2022-12-09 11:52 UTC, VgsStudio commented on src/modules/get_all_students/app/get_all_students_usecase.py
> +            group_selfies_by_ra[selfie.student.ra]["selfies"].append(selfie)
Teoricamente é impossível isso acontecer porque toda selfie tem que ter um student!

Mas coloco sim por precação

2022-12-09 11:53 UTC, VgsStudio commented on src/modules/get_all_students/app/get_all_students_usecase.py
> +            selfies, student = group_selfies_by_ra[raKey]['selfies'], group_selfies_by_ra[raKey]["student"]
declarado!

2022-12-09 11:57 UTC, VgsStudio commented on src/shared/domain/repositories/student_repository_interface.py
> +    def get_all_students(self) -> List[Student]:
não, a método get_all_students retorna TODOS os students no repo.
![image](https://user-images.githubusercontent.com/81604963/206697508-aa0d8b24-67ff-408b-81e3-d708487cd1a4.png)

quem retorna List[Dict] é o usecase 
![image](https://user-images.githubusercontent.com/81604963/206697585-f069d2bc-7231-4612-a67f-1befca05b69c.png)

2022-12-10 14:54 UTC, Brvilardi requested changes

2022-12-10 14:54 UTC, Brvilardi commented on src/modules/get_all_students/app/get_all_students_usecase.py
> +                raise EntityParameterError(message=f"student ra {selfie.student.ra} is unknown")
nao acho que seja uma boa levantar um erro → talvez seja melhor só printar e colocar num ra "00000000", tlg? Ai se der algum erro tipo alguem apagar um student isso nao quebra nosso get all todo

2022-12-13 01:24 UTC, Brvilardi approved these changes
se o soller fez eu acredito

2022-12-13 01:27 UTC, merged