Criação da Rota create_student
Maua-Dev/selfie_mss_student pull request #5
Opened 2022-10-09 15:03 UTC by VgsStudio

Finalizando o <s> CRINGE </s>CRUD do Student. Favor aprovar **primeiro** o PR do update_student pois esse código se baseia naquele.

2022-10-10 01:00 UTC, Brvilardi requested changes

2022-10-10 01:00 UTC, Brvilardi commented on src/helpers/http/http_models.py
> +    def __init__(self, body: Any = None) -> None:
tirar esse None

2022-10-10 01:00 UTC, Brvilardi commented on src/domain/repositories/student_repository_interface.py
> +    def get_student(self, ra: str, email: str) -> Student:
arrumar os atributos da interface pra ser só ra (tirar o email)

2022-10-10 01:00 UTC, Brvilardi commented on src/modules/create_student/create_student_controller.py
> +            return OK()
deve retornar 201 e mandar um body tipo "User {name} was created successfully"

2022-10-10 01:00 UTC, Brvilardi commented on src/infra/repositories/student_repository_mock.py
> +    def create_student(self, ra: str, name: str, email: str) -> None:
metodo nao deve receber os parametros, deve receber um Student

2022-10-10 01:00 UTC, Brvilardi commented on src/modules/create_student/create_student_controller.py
> +
intanciar Student e passar pro usecase essa instancia de Student

2022-10-10 01:00 UTC, Brvilardi commented on src/modules/update_student/update_student_usecase.py
> +        self.repo.update_student(ra=ra, new_name=new_name, new_email=new_email)
cade o erro se tentar atualizar um RA que nao existe?

2022-10-11 00:49 UTC, VgsStudio commented on src/helpers/http/http_models.py
> +    def __init__(self, body: Any = None) -> None:
OK()

2022-10-11 00:52 UTC, VgsStudio commented on src/domain/repositories/student_repository_interface.py
> +    def get_student(self, ra: str, email: str) -> Student:
OK()

2022-10-11 02:47 UTC, VgsStudio commented on src/modules/create_student/create_student_controller.py
> +            return OK()
OK()

2022-10-11 02:56 UTC, VgsStudio commented on src/infra/repositories/student_repository_mock.py
> +    def create_student(self, ra: str, name: str, email: str) -> None:
OK()

2022-10-11 02:56 UTC, VgsStudio commented on src/modules/create_student/create_student_controller.py
> +
OK()

2022-10-11 02:57 UTC, VgsStudio commented on src/modules/update_student/update_student_usecase.py
> +        self.repo.update_student(ra=ra, new_name=new_name, new_email=new_email)
outra branch, vou fazer com o @JoaoVitorBranco

2022-10-11 21:54 UTC, Brvilardi requested changes

2022-10-11 21:54 UTC, Brvilardi commented on src/infra/repositories/student_repository_mock.py
> +    def get_students_by_ra_or_email(self, ra: str = None, email: str = None) -> List[Student]:
se ra AND email forem None, levantar erro de MissingParameters

2022-10-11 22:16 UTC, Brvilardi approved these changes
LGTM

2022-10-11 22:16 UTC, merged