Crud selfie
Maua-Dev/selfie_mss_student pull request #8
Opened 2022-10-12 21:32 UTC by JoaoVitorBranco

2022-10-12 21:34 UTC, JoaoVitorBranco commented
😎

2022-10-20 00:40 UTC, Brvilardi requested changes

2022-10-20 00:40 UTC, Brvilardi commented on .coveragerc
> +exclude_lines =
colocar no gitignore

2022-10-20 00:40 UTC, Brvilardi commented on src/modules/create_selfie/app/create_selfie_usecase.py
> +    def __call__(self, ra: str, url: str) -> Selfie:
sera que vale uma validacao da url? Vamos criar uma validacao pra ver se é https://<algo>.<algo>.*

2022-10-20 00:40 UTC, Brvilardi commented on src/modules/create_selfie/app/create_selfie_usecase.py
> +            dateUpload=datetime.datetime.now(),
essa data nao esta sendo a dataUpload, esta sendo dateCreated. ou muda o nome da variavel ou a estrategia de pegar esse valor

2022-10-20 00:40 UTC, Brvilardi commented on src/modules/create_selfie/app/create_selfie_viewmodel.py
> +        self.student = StudentViewModel(data.student)
criar uma nova viewmodel especifica pra create selfie. É possivel querermos um comportamento diferente aqui

2022-10-20 00:40 UTC, Brvilardi commented on src/modules/delete_selfie/app/delete_selfie_controller.py
> +            if not request.body.get('idSelfie').isdecimal():
vamos jogar essa validação para a Entidade Selfie? Igual esta no student ra

2022-10-20 00:40 UTC, Brvilardi commented on src/modules/delete_selfie/app/delete_selfie_usecase.py
> +        selfie, student = self.repo.delete_selfie(ra=ra, idSelfie=idSelfie)
o que acontece se a Selfie nao existe?

2022-10-20 00:40 UTC, Brvilardi commented on src/modules/delete_selfie/app/delete_selfie_viewmodel.py
> +        return {
vale colocar o Student aqui? (nao sei é uma pergunta mesmo)

2022-10-20 00:40 UTC, Brvilardi commented on src/modules/get_selfie/app/get_selfie_controller.py
> +            if not request.query_params.get('idSelfie').isdecimal():
sera que nao vale colocar isso no comportameno da entidade Selfie?

2022-10-20 00:40 UTC, Brvilardi commented on src/modules/get_selfie/app/get_selfie_viewmodel.py
> +        return {
sera que vale colocar o student

2022-10-21 00:16 UTC, VgsStudio commented on .coveragerc
> +exclude_lines =
OK()

2022-10-21 00:33 UTC, VgsStudio commented on src/modules/create_selfie/app/create_selfie_usecase.py
> +    def __call__(self, ra: str, url: str) -> Selfie:
OK!

2022-10-21 00:37 UTC, VgsStudio commented on src/modules/create_selfie/app/create_selfie_usecase.py
> +            dateUpload=datetime.datetime.now(),
OK¡

2022-10-21 00:40 UTC, VgsStudio commented on src/modules/create_selfie/app/create_selfie_viewmodel.py
> +        self.student = StudentViewModel(data.student)
!OK

2022-10-21 00:43 UTC, VgsStudio commented on src/modules/delete_selfie/app/delete_selfie_controller.py
> +            if not request.body.get('idSelfie').isdecimal():
OK - nem precisei arrumar top

2022-10-21 00:46 UTC, VgsStudio commented on src/modules/delete_selfie/app/delete_selfie_viewmodel.py
> +        return {
SAFE, NEM PRECISEI

2022-10-21 00:46 UTC, VgsStudio commented on src/modules/get_selfie/app/get_selfie_viewmodel.py
> +        return {
SAFE, NEM PRECISEI

2022-10-21 00:55 UTC, VgsStudio commented on src/modules/get_selfie/app/get_selfie_controller.py
> +            if not request.query_params.get('idSelfie').isdecimal():
SAFE, NEM PRECISEI

2022-10-21 01:01 UTC, VgsStudio commented on src/modules/delete_selfie/app/delete_selfie_usecase.py
> +        selfie, student = self.repo.delete_selfie(ra=ra, idSelfie=idSelfie)
o¡k

2022-10-23 21:51 UTC, Brvilardi approved these changes
LGTM

2022-10-23 21:51 UTC, merged